server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    embedded-database-connection: h2
  sql:
    init:
      schema-locations: classpath:ddl/schema.sql

mybatis:
  mapper-locations:
    - classpath:net.eezn.mybatis.mapper/sql-*.xml
  configuration:
    map-underscore-to-camel-case: true
