server:
  port: 8081

spring:
  datasource:
    embedded-database-connection: h2
  h2:
    console:
      enabled: true
      path: /h2
#  sql:
#    init:
#      schema-locations: classpath:ddl/schema.sql

  jpa:
    database: h2
    properties:
      hibernate:
        ddl-auto: create
        show-sql: true
        format_sql: true
        use_sql_comments: true

